import Head from "next/head";
import Header from "@/Components/Header";
import LogoCarousel from "@/Components/LogoCarousel";
// import Banner from "@/Components/Banner";
import ExplorePanel from "@/Components/ExplorePanel";

export default function Home() {
  return (
    <div className="overflow-y-hidden">
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <LogoCarousel />
      <ExplorePanel />
      {/* <Banner /> */}
    </div>
  );
}
